# Generated by Django 2.1.1 on 2018-09-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='图片名')),
                ('img', models.FileField(upload_to='img', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='标签')),
                ('catlog', models.CharField(max_length=20, verbose_name='分类')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('pub_deptment', models.CharField(choices=[('x', '行政部'), ('j', '技术部'), ('p', '产品部'), ('f', '财务'), ('b', 'BOSS')], max_length=2, verbose_name='发布部门')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='问题')),
                ('reward', models.IntegerField(default=0, verbose_name='奖励')),
                ('req_user', models.IntegerField(default=0, verbose_name='需求人数')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('content', models.TextField(verbose_name='内容')),
                ('keyword', models.CharField(choices=[('x', '行政部'), ('j', '技术部'), ('p', '产品部'), ('f', '财务'), ('b', 'BOSS')], max_length=2, verbose_name='关键字')),
                ('flag', models.BooleanField(default=False, verbose_name='标志')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='宝物名字')),
                ('item', models.CharField(max_length=64, verbose_name='道具')),
                ('value', models.IntegerField(default=0, verbose_name='价值')),
                ('store', models.IntegerField(default=0, verbose_name='库存')),
                ('stat', models.IntegerField(choices=[(1, '货足'), (2, '没有货了')], default=1, verbose_name='库存状态')),
                ('flag', models.BooleanField(default=False, verbose_name='达成')),
                ('tcreate_date', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Img', verbose_name='图片')),
            ],
            options={
                'verbose_name': '宝物',
                'verbose_name_plural': '宝物',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.IntegerField(verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('create_datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('currency', models.IntegerField(default=0, verbose_name='微币')),
                ('total_currency', models.IntegerField(default=0, verbose_name='总量')),
                ('token', models.CharField(default='', max_length=256, verbose_name='令牌')),
                ('department', models.CharField(default='', max_length=64, verbose_name='部门')),
                ('is_administer', models.BooleanField(default=False, verbose_name='管理员')),
                ('img', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.Img', verbose_name='图片')),
                ('log', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.Log', verbose_name='日志')),
                ('quest', models.ManyToManyField(to='app.Quest', verbose_name='任物')),
                ('sign', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.Sign', verbose_name='签到')),
                ('treasure', models.ManyToManyField(to='app.Treasure', verbose_name='宝物')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
