# Generated by Django 2.1.1 on 2018-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180926_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_number',
            field=models.IntegerField(default=0, verbose_name='工号'),
        ),
    ]
