# Generated by Django 2.1.1 on 2018-09-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180926_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Log', verbose_name='日志'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sign', verbose_name='签到'),
        ),
    ]
