# Generated by Django 2.1.1 on 2018-09-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180926_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Log', verbose_name='日志'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Sign', verbose_name='签到'),
        ),
    ]
